### ISSUE TITLE
Noob hoping to get lucky with your backup solution , but failing so far...

### ISSUE THREAD

**Issue by yngveskog** [BretFisher/docker-vackup#23]
This is my docker compose file:
`version: '3'
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - dokuwiki_config:/config
    ports:
      - 8081:80
    restart: unless-stopped

volumes:
  dokuwiki_config:`

I'm running: ` vackup export dokuwiki_config backup_dokuwiki.tar.gz` 
and I get a folder called `vackup-volume` but it's empty. What am I doing wrong?

**Comment by BretFisher** [comment]
I think you need to set a name for the volume if you want to use it with compose. Compose adds a prefix to all resources it creates based on directory name (which is fine, I actually prefer it that way, but it does mean you either need to change your command or change the yaml)

This worked for me:

```yaml
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - dokuwiki_config:/config
    ports:
      - 8081:80
    restart: unless-stopped

volumes:
  dokuwiki_config:
    name: dokuwiki_config
```
